/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '15. 4. 27 오전 10:28' with Gradle 2.3
 *
 * @author Administrator, @date 15. 4. 27 오전 10:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
