/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '15. 3. 20 오후 5:12' with Gradle 2.3
 *
 * @author Administrator, @date 15. 3. 20 오후 5:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
